module.exports = {
  'master_news': {
    'wangdai': 'news_wd',
    'gtjx': 'news_wd_gtjx',
    'zjzl': 'news_wd_zjzl',
    'ptdt': 'news_wd_ptdt',
    'zjcp': 'news_wd_zjcp',
    'wdxw': 'news_wd_wdxw',
    'touzi': 'news_tz',
    'tzxm': 'news_tz_tzxm',
    'cytz': 'news_tz_cytz',
    'xetz': 'news_tz_xetz',
    'tzjq': 'news_tz_tzjq',
    'cgtz': 'news_tz_cgtz',
    'licai': 'news_lc',
    'lccp': 'news_lc_lccp',
    'jtlc': 'news_lc_jtlc',
    'grlc': 'news_lc_grlc',
    'yhlc': 'news_lc_yhlc',
    'hlwlc': 'news_lc_hlwlc',
    'yinhang': 'news_yh',
    'yhzs': 'news_yh_yhzs',
    'yhll': 'news_yh_yhll',
    'wsyh': 'news_yh_wsyh',
    'yhk': 'news_yh_yhk',
    'xinyongka': 'news_xyk',
    'xykbl': 'news_xyk_xykbl',
    'xykfq': 'news_xyk_xykfq',
    'xykhk': 'news_xyk_xykhk',
    'jijin': 'news_jj',
    'jjrm': 'news_jj_jjrm',
    'jjdt': 'news_jj_jjdt',
    'hbjj': 'news_jj_hbjj',
    'baoxian': 'news_bx',
    'bxlc': 'news_bx_bxlc',
    'sybx': 'news_bx_sybx',
    'shbx': 'news_bx_shbx',
    'ywbx': 'news_bx_ywbx'
  },
  'master_wiki': {
    'wdbk': 'wiki_wd',
    'tzbk': 'wiki_tz',
    'lcbk': 'wiki_lc',
    'yhbk': 'wiki_yh',
    'xykbk': 'wiki_xyk',
    'jjbk': 'wiki_jj',
    'bxbk': 'wiki_bx'
  },
  'master_special': {
    'wdzt': 'special_wd',
    'tzzt': 'special_tz',
    'lczt': 'special_lc',
    'yhzt': 'special_yh',
    'xykzt': 'special_xyk',
    'jjzt': 'special_jj',
    'bxzt': 'special_bx'
  }
}